_updated_at: 1772982055
_updated_by: system
_version: 5
conflicts: []
groups:
- bindings:
  - kind: os
    path: robot.motion.max_speed_mps
  - app_id: app_hello_world_examle_2026030816_4753
    app_version: 0.1.0
    kind: app
    path: robot.motion.max_speed_mps
  group_id: magnet__robot__motion__max_speed_mps
  path: robot.motion.max_speed_mps
  value: 1.25
  value_type: number
