version: '1.0'
name: aivudaos-build-publish-wheel
displayName: aivudaos-build-publish-wheel
triggers:
  trigger: manual
  push:
    branches:
      include:
        - main
stages:
  - name: build
    displayName: Build Python distributions
    strategy: naturally
    trigger: auto
    steps:
      - step: build@python
        name: build_python_package
        displayName: Build and optionally publish AivudaOS
        pythonVersion: '3.8'
        commands:
          - ''
          - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
          - apt install -y nodejs
          - ''
          - python --version
          - node --version
          - npm --version
          - ''
          - export PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
          - export PIP_DEFAULT_TIMEOUT=100
          - ''
          - export AIVUDAOS_BUILD_DATE="$(date -u +%Y%m%d)"
          - export AIVUDAOS_BUILD_SEQ="${GITEE_PIPELINE_BUILD_NUMBER}"
          - export TWINE_USERNAME=__token__
          - export TWINE_PASSWORD="${PYPI_TOKEN:-}"
          - export PYPI_UPLOAD="${ENABLE_PYPI_UPLOAD:-false}"
          - ''
          - if [ "${PYPI_UPLOAD}" = "true" ] && [ -n "${TWINE_PASSWORD:-}" ]; then
          - '  export TWINE_NON_INTERACTIVE=1'
          - '  echo -e "\e[32menable uploading pypi, since PYPI_UPLOAD = true && TWINE_PASSWORD is set\e[0m"'
          - '  ./publish_aivudaos_pypi.sh'
          - else
          - '  echo -e "\e[32mdisable uploading pypi, since PYPI_UPLOAD = false or TWINE_PASSWORD is not set\e[0m"'
          - '  ./publish_aivudaos_pypi.sh --skip-upload'
          - fi
          - ''
          - ls -lah dist
          - ''
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        strategy: {}
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: aivudaos-latest-dist
        notify: []
        strategy:
          retry: '0'
        dependsOn: build_python_package
  - name: stage-2adb8f4b
    displayName: release
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: aivudaos-latest-dist
        version: 1.0.0.0
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'
